- public/index.html
https://github.com/edx/front-end-cookie-cutter-application/pull/154/
> Corrects routing to allow for multiple

- package-lock.json
- package.json
- src/data/reducers/index.js
Redux Forms getting started docs
https://redux-form.com/7.4.2/docs/gettingstarted.md/
> Add redux-forms to support adding forms in React using redux

- public/index.html
Basing this PR off of https://github.com/edx/gradebook/blob/2cc14191b4181245326e5ed1f25113ba63681e14/public/index.html
> Updating index.html

- package-lock.json
- src/components/CourseTable/__snapshots__/CourseTable.test.jsx.snap
- src/components/CourseTable/index.jsx
- src/components/CreateCoursePage/__snapshots__/CreateCourseForm.test.jsx.snap
- src/components/CreateCoursePage/__snapshots__/CreateCoursePage.test.jsx.snap
- src/components/RenderInputTextField/__snapshots__/RenderInputTextField.test.jsx.snap
- src/components/RenderSelectField/__snapshots__/RenderSelectField.test.jsx.snap
- src/components/TableComponent/__snapshots__/TableComponent.test.jsx.snap
Quick PR to Center the table and add a New Course Button
> Added a New Course button

- src/components/StaffGrid/StaffGrid.test.jsx
This isn't the most beautiful thing in the world, and it isn't as black-box as I'd like it to be, but it verifies that we can move things around in the list.
> Add a test for drag-and-drop functionality.

- package-lock.json
- package.json
Reverts edx/publisher-frontend#60
> Revert "Update connected-react-router to the latest version 🚀"

- src/components/CreateCoursePage/__snapshots__/CreateCoursePage.test.jsx.snap
- src/components/CreateCoursePage/index.jsx
- src/components/CreateCourseRunPage/CreateCourseRunForm.jsx
- src/components/CreateCourseRunPage/CreateCourseRunForm.test.jsx
- src/components/CreateCourseRunPage/CreateCourseRunPage.test.jsx
- src/components/CreateCourseRunPage/__snapshots__/CreateCourseRunForm.test.jsx.snap
- src/components/CreateCourseRunPage/__snapshots__/CreateCourseRunPage.test.jsx.snap
- src/components/CreateCourseRunPage/index.jsx
- src/components/EditCoursePage/CollapsibleCourseRunFields.jsx
- src/components/EditCoursePage/CollapsibleCourseRunFields.test.jsx
- src/components/EditCoursePage/EditCourseForm.jsx
- src/components/EditCoursePage/__snapshots__/CollapsibleCourseRunFields.test.jsx.snap
- src/components/EditCoursePage/__snapshots__/EditCoursePage.test.jsx.snap
- src/components/EditCoursePage/index.jsx
- src/containers/CreateCourseRun/index.jsx
- src/data/actions/courseInfo.js
- src/data/reducers/courseInfo.js
- src/data/reducers/courseInfo.test.js
- src/index.jsx
Added the Create Course run form. Planning to rebase on the upcoming changes.
> Adding Course Run Create form and button

- src/components/EditCoursePage/EditCourseForm.jsx
- src/components/EditCoursePage/EditCourseForm.test.jsx
- src/components/EditCoursePage/__snapshots__/EditCourseForm.test.jsx.snap
- src/components/EditCoursePage/__snapshots__/EditCoursePage.test.jsx.snap
- src/components/EditCoursePage/index.jsx
- src/utils.js
- src/utils.test.js
Identify form by the course uuid so that the changes on one form do
not cross over to the other course edit forms.
> Uniquely identify course-edit-form

- src/components/CourseTable/__snapshots__/CourseTable.test.jsx.snap
- src/components/CourseTable/index.jsx
- src/components/CreateCoursePage/CreateCourseForm.jsx
- src/components/CreateCoursePage/CreateCourseForm.test.jsx
- src/components/CreateCoursePage/CreateCoursePage.test.jsx
- src/components/CreateCoursePage/__snapshots__/CreateCourseForm.test.jsx.snap
- src/components/CreateCoursePage/__snapshots__/CreateCoursePage.test.jsx.snap
Updates to the Create Course Page to new format to better support snapshot tests.
> updated Create Course Page and tests

- src/components/EditCoursePage/EditCourseForm.jsx
- src/components/EditCoursePage/__snapshots__/EditCourseForm.test.jsx.snap
https://openedx.atlassian.net/browse/DISCO-748
> Make fewer course fields required to save

- src/components/EditCoursePage/CollapsibleCourseRunFields.jsx
- src/components/EditCoursePage/EditCourseForm.jsx
- src/components/EditCoursePage/__snapshots__/CollapsibleCourseRunFields.test.jsx.snap
- src/components/EditCoursePage/__snapshots__/EditCourseForm.test.jsx.snap
> WIP: Add submit button to each course run

- Makefile
- src/App.scss
- src/components/ButtonToolbar/index.jsx
- src/components/CourseTable/__snapshots__/CourseTable.test.jsx.snap
- src/components/CourseTable/index.jsx
- src/components/CreateCoursePage/CreateCourseForm.jsx
- src/components/CreateCoursePage/__snapshots__/CreateCourseForm.test.jsx.snap
- src/components/CreateCoursePage/__snapshots__/CreateCoursePage.test.jsx.snap
- src/components/CreateCoursePage/index.jsx
- src/components/CreateCourseRunPage/CreateCourseRunForm.jsx
- src/components/CreateCourseRunPage/__snapshots__/CreateCourseRunForm.test.jsx.snap
- src/components/CreateCourseRunPage/__snapshots__/CreateCourseRunPage.test.jsx.snap
- src/components/CreateCourseRunPage/index.jsx
- src/components/EditCoursePage/CollapsibleCourseRunFields.jsx
- src/components/EditCoursePage/EditCourseForm.jsx
- src/components/EditCoursePage/__snapshots__/CollapsibleCourseRunFields.test.jsx.snap
- src/components/EditCoursePage/__snapshots__/EditCourseForm.test.jsx.snap
- src/components/EditCoursePage/__snapshots__/EditCoursePage.test.jsx.snap
- src/components/EditCoursePage/index.jsx
- src/components/Header/__snapshots__/Header.test.jsx.snap
- src/components/Header/index.jsx
- src/components/PageContainer/index.jsx
- src/components/TableComponent/__snapshots__/TableComponent.test.jsx.snap
- src/components/TableComponent/index.jsx
* Adds a PageContainer component that just stores the container/row/col wrapper that we expect for our forms. We don't need multiple rows or columns, since forms have their own internal arrangements.
* Adds a ButtonToolbar to wrap all of our button rows. There are nice html5 wrappers for groups of buttons that we should apparently use. This makes it easier.
* Get rid of a bunch of duplicate row and column definitions.
> Make container usage more consistent

- src/components/CreateCoursePage/CreateCourseForm.jsx
- src/components/CreateCoursePage/__snapshots__/CreateCourseForm.test.jsx.snap
- src/components/CreateCourseRunPage/CreateCourseRunForm.jsx
- src/components/CreateCourseRunPage/__snapshots__/CreateCourseRunForm.test.jsx.snap
- src/components/CreateInstructorPage/__snapshots__/AreasOfExpertise.test.jsx.snap
- src/components/CreateInstructorPage/__snapshots__/SocialLinks.test.jsx.snap
- src/components/EditCoursePage/CollapsibleCourseRunFields.jsx
- src/components/EditCoursePage/EditCourseForm.jsx
- src/components/EditCoursePage/TranscriptLanguage.jsx
- src/components/EditCoursePage/__snapshots__/CollapsibleCourseRunFields.test.jsx.snap
- src/components/EditCoursePage/__snapshots__/EditCourseForm.test.jsx.snap
- src/components/EditCoursePage/__snapshots__/TranscriptLanguage.test.jsx.snap
- src/components/FieldLabel/index.jsx
- src/components/RemoveButton/__snapshots__/RemoveButton.test.jsx.snap
- src/components/RemoveButton/index.jsx
- src/components/RichEditor/__snapshots__/RichEditor.test.jsx.snap
- src/components/RichEditor/index.jsx
- src/components/StaffList/__snapshots__/StaffList.test.jsx.snap
- src/components/StaffList/index.jsx
This standardizes the look of field labels. I also corrected some spacing where I could between fields.
I'm still ignoring the instructor page, since it's about to be refactored.
> Add FieldLabel class and use it on every field

- src/components/EditCoursePage/CollapsibleCourseRunFields.jsx
- src/components/EditCoursePage/CollapsibleCourseRunFields.test.jsx
- src/components/EditCoursePage/EditCourseForm.jsx
- src/components/EditCoursePage/EditCourseForm.test.jsx
- src/components/EditCoursePage/__snapshots__/CollapsibleCourseRunFields.test.jsx.snap
- src/components/EditCoursePage/__snapshots__/EditCourseForm.test.jsx.snap
- src/components/EditCoursePage/__snapshots__/EditCoursePage.test.jsx.snap
- src/components/EditCoursePage/index.jsx
- src/components/RichEditor/__snapshots__/RichEditor.test.jsx.snap
- src/components/RichEditor/index.jsx
- src/data/constants/index.js
https://openedx.atlassian.net/browse/DISCO-757
Disables all course fields if any of the course runs are in review.
> Disable fields when a course run is in review.

- src/components/EditCoursePage/CollapsibleCourseRunFields.jsx
- src/components/EditCoursePage/TranscriptLanguage.jsx
- src/components/EditCoursePage/__snapshots__/CollapsibleCourseRunFields.test.jsx.snap
- src/components/EditCoursePage/__snapshots__/TranscriptLanguage.test.jsx.snap
- src/components/StaffList/__snapshots__/StaffList.test.jsx.snap
- src/components/StaffList/index.jsx
- src/components/Staffer/__snapshots__/Staffer.test.jsx.snap
- src/components/Staffer/index.jsx
https://openedx.atlassian.net/browse/DISCO-757
Disable all the things!
> Allow disabling of staff list and transcript languages.

- package-lock.json
- package.json
- src/data/actions/courseInfo.test.js
- src/data/actions/courseOptions.test.js
- src/data/actions/courseRunOptions.test.js
- src/data/actions/publisherUserInfo.test.js
- src/data/actions/stafferOptions.test.js
- src/data/actions/table.test.js
- src/index.jsx
The 4.0.0 version of frontend-auth resolves an issue where users would be prompted to login more frequently than necessary when reloading the app.
> Upgrade frontend-auth to 4.0.0

- src/App.scss
- src/components/RichEditor/RichEditor.scss
- src/components/RichEditor/__snapshots__/RichEditor.test.jsx.snap
- src/components/RichEditor/index.jsx
https://openedx.atlassian.net/browse/DISCO-757
This is mostly a visual cleanup to make the fields look more consistent.
> Style rich text editor components to look like other disabled fields.

- src/components/EditCoursePage/EditCourseForm.jsx
- src/components/EditCoursePage/TranscriptLanguage.jsx
- src/components/EditCoursePage/__snapshots__/EditCourseForm.test.jsx.snap
- src/components/EditCoursePage/__snapshots__/TranscriptLanguage.test.jsx.snap
- src/components/RemoveButton/__snapshots__/RemoveButton.test.jsx.snap
- src/components/RemoveButton/index.jsx
- src/components/StafferPage/AreasOfExpertise.jsx
- src/components/StafferPage/SocialLinks.jsx
- src/components/StafferPage/StafferForm.jsx
- src/components/StafferPage/__snapshots__/AreasOfExpertise.test.jsx.snap
- src/components/StafferPage/__snapshots__/SocialLinks.test.jsx.snap
- src/components/StafferPage/__snapshots__/Staffer.test.jsx.snap
- src/components/StafferPage/__snapshots__/StafferPage.test.jsx.snap
- src/components/StafferPage/index.jsx
This also unifies the look of our "list of widgets" bits like areas of expertise and transcript languages. We should make a component to standardize the look. But for now, they it's just very similar code.
> Make staff page prettier, plus some other style fixes

- src/components/StaffList/__snapshots__/StaffList.test.jsx.snap
- src/components/StaffList/index.jsx
This passes through the disabled argument so that autosuggest is also disabled when the StaffList is disabled.
> Disable autosuggest when StaffList is disabled.

- src/components/EditCoursePage/CollapsibleCourseRunFields.scss
- src/components/StaffList/StaffList.scss
- src/components/StaffList/__snapshots__/StaffList.test.jsx.snap
- src/components/StaffList/index.jsx
- src/sass/App.scss
> Making autosuggest item list expand container dynamically.

- decisions/0002-new-instructor-org-association.rst
> Adding ADR about new-instructors association to org

- src/components/Pill/Pill.test.jsx
- src/components/Pill/__snapshots__/Pill.test.jsx.snap
Fixes <img width="850" alt="Screen Shot 2019-04-22 at 1 49 48 PM" src="https://user-images.githubusercontent.com/14864970/56515616-426a9080-6506-11e9-861f-9edb15d13a50.png">
> Fix props warning on pills test

- src/components/EditCoursePage/CollapsibleCourseRunFields.jsx
- src/components/EditCoursePage/EditCourseForm.jsx
- src/components/EditCoursePage/__snapshots__/CollapsibleCourseRunFields.test.jsx.snap
- src/components/EditCoursePage/__snapshots__/EditCourseForm.test.jsx.snap
DISCO-828
Actual validation to come in a separate PR
> Add required for submission label to courses/runs

- src/components/EditCoursePage/EditCourseForm.jsx
- src/components/EditCoursePage/EditCourseForm.scss
- src/components/EditCoursePage/__snapshots__/EditCourseForm.test.jsx.snap
- src/components/ImageUpload/__snapshots__/ImageUpload.test.jsx.snap
- src/components/ImageUpload/index.jsx
- src/components/StafferPage/StafferForm.jsx
- src/components/StafferPage/StafferForm.scss
- src/components/StafferPage/__snapshots__/StafferForm.test.jsx.snap
- src/sass/App.scss
> Set a maximum height/width for uploaded images

- src/components/StaffList/StaffList.test.jsx
- src/components/StaffList/index.jsx
- src/data/services/DiscoveryDataApiService.js
> Update to use new DRF endpoint

- package-lock.json
- src/components/EditCoursePage/CollapsibleCourseRunFields.jsx
- src/components/EditCoursePage/CollapsibleCourseRunFields.test.jsx
- src/components/EditCoursePage/EditCourseForm.jsx
- src/components/EditCoursePage/EditCourseForm.test.jsx
- src/components/EditCoursePage/EditCoursePage.test.jsx
- src/components/EditCoursePage/__snapshots__/CollapsibleCourseRunFields.test.jsx.snap
- src/components/EditCoursePage/__snapshots__/EditCourseForm.test.jsx.snap
- src/components/EditCoursePage/__snapshots__/EditCoursePage.test.jsx.snap
- src/components/EditCoursePage/index.jsx
This doesn't do any of the custom validation or focus management stuff, just triggers which fields are required or not based off what triggered the edit course form submission
> Mark different fields as required depending on submit source

- src/components/EditCoursePage/CollapsibleCourseRunFields.jsx
- src/components/EditCoursePage/EditCourseForm.jsx
- src/components/EditCoursePage/__snapshots__/CollapsibleCourseRunFields.test.jsx.snap
- src/components/EditCoursePage/__snapshots__/EditCourseForm.test.jsx.snap
- src/components/FieldHelp/index.jsx
> Add more tooltips

- config/webpack.dev.config.js
- src/components/EditCoursePage/CollapsibleCourseRunFields.jsx
- src/components/EditCoursePage/EditCourseForm.jsx
- src/components/EditCoursePage/__snapshots__/CollapsibleCourseRunFields.test.jsx.snap
- src/components/EditCoursePage/__snapshots__/EditCourseForm.test.jsx.snap
- src/components/EditCoursePage/index.jsx
- Stop getting logged out in devstack every hour (though you will still
be redirected to the LMS every hour)
- Have the submit-for-review button show a pending state
- Have the submit-for-review button be enabled even if other course runs
are in review
- Make course and course run section headers larger
- Don't submit course runs that are in review to the backend - it will
just reject them
- Don't mark 'Course pacing' as required for submit - it doesn't have
an empty state in the first place
DISCO-854
DISCO-857
> A few small fixes

- src/components/EditCoursePage/CollapsibleCourseRunFields.jsx
- src/components/EditCoursePage/EditCourseForm.jsx
- src/components/EditCoursePage/__snapshots__/CollapsibleCourseRunFields.test.jsx.snap
- src/components/EditCoursePage/__snapshots__/EditCourseForm.test.jsx.snap
Feedback from Julia, and adding more readthedocs links.
> More tooltip tweaks

- src/components/CreateCoursePage/CreateCourseForm.jsx
- src/components/CreateCoursePage/__snapshots__/CreateCourseForm.test.jsx.snap
- src/components/CreateCourseRunPage/CreateCourseRunForm.jsx
- src/components/CreateCourseRunPage/__snapshots__/CreateCourseRunForm.test.jsx.snap
- src/components/EditCoursePage/CollapsibleCourseRunFields.jsx
- src/components/EditCoursePage/EditCourseForm.jsx
- src/helpText.jsx
> Add tooltips when creating a course or a run

- src/components/Pill/__snapshots__/Pill.test.jsx.snap
- src/components/Pill/index.jsx
> Updated the colors and text to highlight new/unsubmitted

- src/components/CreateCoursePage/CreateCourseForm.jsx
- src/components/CreateCoursePage/CreateCourseForm.test.jsx
- src/components/CreateCoursePage/__snapshots__/CreateCourseForm.test.jsx.snap
- src/components/CreateCoursePage/__snapshots__/CreateCoursePage.test.jsx.snap
- src/components/CreateCoursePage/index.jsx
- src/components/EditCoursePage/EditCourseForm.jsx
- src/components/EditCoursePage/EditCourseForm.test.jsx
- src/components/EditCoursePage/EditCoursePage.test.jsx
- src/components/EditCoursePage/__snapshots__/EditCourseForm.test.jsx.snap
- src/components/EditCoursePage/__snapshots__/EditCoursePage.test.jsx.snap
- src/components/EditCoursePage/index.jsx
- src/components/Pill/index.jsx
- src/containers/CreateCourse/index.jsx
- src/containers/EditCourse/index.jsx
- src/data/constants/index.js
update the course after it has gone live. Fixing price on create and edit to detect and send changes.
Also allowing updates to mode and price until a course run is in review. Price will be hidden unless the mode is professional or verified.
> Updating the frontend to send an indicator variable for when we should

- src/components/StafferPage/StafferForm.jsx
- src/components/StafferPage/__snapshots__/StafferForm.test.jsx.snap
> Updates according to Carol feedback

- package.json
- src/index.jsx
Note: This is a fix-forward PR.
The `@edx/frontend-component-footer` package now requires the app to be wrapped in the `IntlProvider` component from `react-intl`. This is why we're currently seeing JS errors on stage for publisher. 
Including the `IntlProvider` component should resolve these errors.
> Wrap app with IntlProvider from react-intl

- src/components/EditCoursePage/index.jsx
saves when going back to empty values.
> Fixing failed save when number fields are blank. Also fixes pristine

- src/data/services/DiscoveryDataApiService.js
Small PR to help have URLs match when being returned from PATCH.
> update to add utm exclusion to url params

- src/components/EditCoursePage/CollapsibleCourseRun.jsx
- src/components/EditCoursePage/EditCourseForm.jsx
- src/components/EditCoursePage/EditCourseForm.test.jsx
- src/components/EditCoursePage/EditCoursePage.test.jsx
- src/components/EditCoursePage/__snapshots__/CollapsibleCourseRun.test.jsx.snap
- src/components/EditCoursePage/__snapshots__/EditCourseForm.test.jsx.snap
- src/components/EditCoursePage/__snapshots__/EditCoursePage.test.jsx.snap
- src/components/EditCoursePage/index.jsx
[DISCO-944]
changes to support adding expected program type and name
[DISCO-944]: https://openedx.atlassian.net/browse/DISCO-944
> updates to add program type and name to course run forms

- src/components/CreateCoursePage/CreateCourseForm.jsx
- src/components/CreateCoursePage/CreateCourseForm.test.jsx
- src/components/CreateCoursePage/__snapshots__/CreateCourseForm.test.jsx.snap
- src/components/CreateCoursePage/__snapshots__/CreateCoursePage.test.jsx.snap
- src/components/CreateCoursePage/index.jsx
- src/components/CreateCourseRunPage/CreateCourseRunForm.jsx
- src/components/CreateCourseRunPage/CreateCourseRunForm.test.jsx
- src/components/CreateCourseRunPage/__snapshots__/CreateCourseRunForm.test.jsx.snap
- src/components/CreateCourseRunPage/__snapshots__/CreateCourseRunPage.test.jsx.snap
- src/components/CreateCourseRunPage/index.jsx
- src/components/EditCoursePage/CollapsibleCourseRun.jsx
- src/components/EditCoursePage/EditCourseForm.jsx
- src/components/EditCoursePage/__snapshots__/CollapsibleCourseRun.test.jsx.snap
- src/components/EditCoursePage/__snapshots__/EditCourseForm.test.jsx.snap
- src/containers/CreateCourse/CreateCourse.test.jsx
- src/containers/CreateCourse/index.jsx
- src/containers/CreateCourseRun/index.jsx
- src/helpText.jsx
**Several minor adjustments from alpha feedback**
- Added Pacing to create new Course and new Course Run form.
- Save button made a primary button.
- Start and end dates given a time
Publish date:
- Add to tooltip: “To publish as soon as possible, set the publish date to today. Please note that changes may take 48 hours to go live.” (Review this with Carol)
- Add to tooltip: “If you don’t have a publish date yet, set to 1 year in the future.”
- Publish Date field made a required field
- Publish Date displayed on collapse
> ciduarte/DISCO-1010 Small workflow adjustments

- src/components/CourseTable/__snapshots__/CourseTable.test.jsx.snap
- src/components/CourseTable/index.jsx
- src/components/Header/__snapshots__/Header.test.jsx.snap
- src/components/Header/index.jsx
Added a banner on publisher home page to alert
users that it is the beta version.
DISCO-1108
> Beta Publisher Alert

- src/components/CreateCoursePage/CreateCourseForm.jsx
- src/components/CreateCoursePage/__snapshots__/CreateCourseForm.test.jsx.snap
- src/components/CreateCourseRunPage/CreateCourseRunForm.jsx
- src/components/CreateCourseRunPage/__snapshots__/CreateCourseRunForm.test.jsx.snap
- src/components/CreateCourseRunPage/index.jsx
- src/components/DateTimeField/index.jsx
- src/components/EditCoursePage/CollapsibleCourseRun.jsx
- src/components/EditCoursePage/__snapshots__/CollapsibleCourseRun.test.jsx.snap
- src/components/EditCoursePage/index.jsx
- src/utils/index.js
Added new fields to input time alongside dates
> ciduarte/DISCO-1010 Adding Time to Start & End Date

- public/index.html
Renamed page title from 'Publisher Alpha' to
'Publisher Beta'
DISCO-1108
> Page title changed to 'Publisher Beta'

- src/data/actions/courseInfo.js
- src/data/services/DiscoveryDataApiService.js
[DISCO-1087]
[DISCO-1087]: https://openedx.atlassian.net/browse/DISCO-1087
> Course data will now be sent before Course Run on Edit

- config/webpack.dev.config.js
- config/webpack.prod.config.js
- src/components/CourseTable/CourseTable.test.jsx
- src/components/CourseTable/__snapshots__/CourseTable.test.jsx.snap
- src/components/CourseTable/index.jsx
- src/containers/CourseDashboard/index.jsx
[DISCO-1129]
[DISCO-1129]: https://openedx.atlassian.net/browse/DISCO-1129
> Add ability to limit orgs with access to Publisher to a white list.

- src/components/CreateCoursePage/CreateCourseForm.jsx
- src/components/CreateCoursePage/__snapshots__/CreateCourseForm.test.jsx.snap
- src/components/CreateCourseRunPage/CreateCourseRunForm.jsx
- src/components/CreateCourseRunPage/__snapshots__/CreateCourseRunForm.test.jsx.snap
- src/components/CreateCourseRunPage/__snapshots__/CreateCourseRunPage.test.jsx.snap
- src/components/CreateCourseRunPage/index.jsx
- src/components/DateTimeField/index.jsx
- src/components/EditCoursePage/CollapsibleCourseRun.jsx
- src/components/EditCoursePage/EditCourseForm.jsx
- src/components/EditCoursePage/__snapshots__/CollapsibleCourseRun.test.jsx.snap
- src/components/EditCoursePage/__snapshots__/EditCourseForm.test.jsx.snap
- src/containers/CreateCourseRun/index.jsx
- src/utils/validation.js
The following validations were added:
Price ($1 - $10,000)
Start Date: Today or later
End Date: Must be after Start Date
Publish Date: Today or later
Min/Max Hours: greater than zero and less than 168
DISCO-1097
> Add Course Edit form restrictions

- config/webpack.dev.config.js
- config/webpack.prod.config.js
- src/components/CourseTable/index.jsx
- src/components/CreateCoursePage/__snapshots__/CreateCourseForm.test.jsx.snap
- src/components/CreateCourseRunPage/__snapshots__/CreateCourseRunForm.test.jsx.snap
- src/components/EditCoursePage/__snapshots__/CollapsibleCourseRun.test.jsx.snap
[DISCO-1129]
[DISCO-1129]: https://openedx.atlassian.net/browse/DISCO-1129
> whitelist is now a csv string rather than an array

- src/components/CreateCoursePage/__snapshots__/CreateCourseForm.test.jsx.snap
- src/components/CreateCourseRunPage/__snapshots__/CreateCourseRunForm.test.jsx.snap
- src/components/EditCoursePage/EditCourseForm.jsx
- src/components/EditCoursePage/__snapshots__/CollapsibleCourseRun.test.jsx.snap
- src/components/EditCoursePage/__snapshots__/EditCourseForm.test.jsx.snap
- src/components/EditCoursePage/index.jsx
Adding in more defensive checks against assuming entitlements already exist. Switching the default order of enrollment track options to have audit be the default display if there is no value.
DISCO-1082
> Handling official version course  no entitlement

- src/components/CreateCoursePage/CreateCourseForm.test.jsx
- src/components/CreateCoursePage/__snapshots__/CreateCourseForm.test.jsx.snap
- src/components/CreateCourseRunPage/CreateCourseRunForm.test.jsx
- src/components/CreateCourseRunPage/__snapshots__/CreateCourseRunForm.test.jsx.snap
- src/components/DateTimeField/index.jsx
- src/components/EditCoursePage/CollapsibleCourseRun.jsx
- src/components/EditCoursePage/CollapsibleCourseRun.test.jsx
- src/components/EditCoursePage/__snapshots__/CollapsibleCourseRun.test.jsx.snap
> Fix Start Date bugs and snapshots

- src/components/CreateCoursePage/__snapshots__/CreateCourseForm.test.jsx.snap
- src/components/CreateCourseRunPage/__snapshots__/CreateCourseRunForm.test.jsx.snap
- src/components/EditCoursePage/CollapsibleCourseRun.jsx
- src/components/EditCoursePage/EditCourseForm.jsx
- src/components/EditCoursePage/__snapshots__/CollapsibleCourseRun.test.jsx.snap
- src/components/EditCoursePage/__snapshots__/EditCourseForm.test.jsx.snap
- src/components/EditCoursePage/__snapshots__/TranscriptLanguage.test.jsx.snap
- src/components/FieldLabel/index.jsx
- src/components/StafferPage/StafferForm.jsx
- src/components/StafferPage/__snapshots__/AreasOfExpertise.test.jsx.snap
- src/components/StafferPage/__snapshots__/SocialLinks.test.jsx.snap
- src/components/StafferPage/__snapshots__/StafferForm.test.jsx.snap
Removed both "required" and "required for submit"
field labels. Added in "optional" labels.
DISCO-1112
> Optional field labels

- src/components/CreateCoursePage/CreateCourseForm.jsx
- src/components/CreateCoursePage/__snapshots__/CreateCourseForm.test.jsx.snap
- src/components/CreateCourseRunPage/__snapshots__/CreateCourseRunForm.test.jsx.snap
- src/components/EditCoursePage/EditCourseForm.jsx
- src/components/EditCoursePage/__snapshots__/CollapsibleCourseRun.test.jsx.snap
- src/components/EditCoursePage/__snapshots__/EditCourseForm.test.jsx.snap
- src/components/FieldLabel/index.jsx
- src/components/StafferPage/SocialLinks.jsx
- src/components/StafferPage/__snapshots__/SocialLinks.test.jsx.snap
- src/helpText.jsx
> Update tooltips and other helpers

- src/components/CourseTable/index.jsx
- src/components/CreateCoursePage/CreateCourseForm.jsx
- src/components/CreateCoursePage/__snapshots__/CreateCourseForm.test.jsx.snap
- src/components/DateTimeField/index.jsx
- src/components/EditCoursePage/CollapsibleCourseRun.jsx
- src/components/EditCoursePage/__snapshots__/CollapsibleCourseRun.test.jsx.snap
- src/components/EditCoursePage/__snapshots__/EditCoursePage.test.jsx.snap
- src/components/EditCoursePage/index.jsx
- src/components/StafferPage/StafferForm.jsx
- src/components/StafferPage/__snapshots__/StafferForm.test.jsx.snap
- src/sass/App.scss
Altered labels and tooltips. Updated collapsible so
when a run is published, the "Publish Date" field is
disabled in the form. New course runs given a default
time of 12PM. Cancel button added to New Course form.
DISCO-1184
> Various UI updates

- src/components/CreateCourseRunPage/CreateCourseRunForm.jsx
- src/components/CreateCourseRunPage/__snapshots__/CreateCourseRunForm.test.jsx.snap
- src/components/CreateCourseRunPage/__snapshots__/CreateCourseRunPage.test.jsx.snap
- src/components/CreateCourseRunPage/index.jsx
- src/components/EditCoursePage/__snapshots__/EditCoursePage.test.jsx.snap
- src/components/EditCoursePage/index.jsx
- src/components/PageContainer/index.jsx
- src/components/SidePanes/Pane.jsx
- src/components/SidePanes/UsersPane.jsx
- src/components/SidePanes/UsersPane.test.jsx
Added a cancel button to 'add/set editor',
made the select field a paragon component,
CSS edits made to clean up trickle down of
PageContainer on other pages.
DISCO-1050
> Updates to side pane UI

- src/components/SidePanes/UsersPane.jsx
> Fix for selecting editor bug

- src/components/CourseTable/__snapshots__/CourseTable.test.jsx.snap
- src/components/CourseTable/index.jsx
- src/components/EditCoursePage/index.jsx
Previously, clearing one status alert would clear all
of the status alerts visible. Separated the dismissAlert
logic to allow the alerts to be cleared one at a time.
> Search bar styling and clear status alerts

- package-lock.json
- package.json
https://openedx.atlassian.net/browse/DISCO-1298
> Bump frontend-auth version for redirect fix

- src/components/CreateCoursePage/CreateCourseForm.jsx
- src/components/CreateCoursePage/__snapshots__/CreateCourseForm.test.jsx.snap
- src/components/CreateCoursePage/index.jsx
- src/components/EditCoursePage/EditCourseForm.jsx
- src/components/EditCoursePage/__snapshots__/EditCourseForm.test.jsx.snap
- src/components/EditCoursePage/__snapshots__/EditCoursePage.test.jsx.snap
- src/components/EditCoursePage/index.jsx
- src/data/actions/courseInfo.js
- src/data/services/DiscoveryDataApiService.js
- src/helpText.jsx
add optional flag and update form after save
fix tests, lint
Add help text
> add new field to publisher

- src/components/EditCoursePage/CollapsibleCourseRun.jsx
- src/components/EditCoursePage/CollapsibleCourseRun.test.jsx
- src/components/EditCoursePage/index.jsx
- src/data/constants/index.js
- src/utils/index.js
- src/utils/utils.test.js
change notification message when a reviewed run stays in review after a change.  Change button to disabled when no changes are made, and change label according to if exempt or non-exempt fields are changed
> DISCO-1307 status change exempt

- src/components/EditCoursePage/index.jsx
if published run is edited, show 'Course Run Updated.' in notification
> DISCO-1314 published run edit notification

- src/components/CreateCoursePage/__snapshots__/CreateCourseForm.test.jsx.snap
- src/components/CreateCourseRunPage/__snapshots__/CreateCourseRunForm.test.jsx.snap
- src/components/EditCoursePage/CollapsibleCourseRun.jsx
- src/components/EditCoursePage/__snapshots__/CollapsibleCourseRun.test.jsx.snap
- src/helpText.jsx
When editing. User must still set them on run creation.
https://openedx.atlassian.net/browse/DISCO-1311
> Make start/end dates read-only

- src/components/EditCoursePage/CollapsibleCourseRun.jsx
- src/components/EditCoursePage/__snapshots__/CollapsibleCourseRun.test.jsx.snap
- src/helpText.jsx
> Give more help on dates

- src/components/EditCoursePage/EditCourseForm.jsx
- src/components/EditCoursePage/EditCoursePage.test.jsx
- src/components/EditCoursePage/__snapshots__/EditCoursePage.test.jsx.snap
- src/components/EditCoursePage/index.jsx
- src/utils/validation.js
- src/utils/validation.test.js
If you created a new staff member after already having a staff submission error, sometimes that error would hang around. Now it is cleared correctly.
https://openedx.atlassian.net/browse/DISCO-1312
> Fix staff submission error clearing

- README.md
- decisions/0001-long-term-configuration.rst
- decisions/0002-new-instructor-org-association.rst
- package-lock.json
- package.json
Related PRs:
- https://github.com/edx/edx-gomatic/pull/576
- https://github.com/edx/course-discovery/pull/2142
- https://github.com/edx/terraform/pull/1852
> Rename publisher-frontend to frontend-app-publisher

- src/components/EditCoursePage/__snapshots__/CollapsibleCourseRun.test.jsx.snap
- src/helpText.jsx
Note that data syncs from Studio can take up to a day.
https://openedx.atlassian.net/browse/DISCO-1356
(I also changed "pacing type" to "course pacing" which is the actual field label.)
> Add a note that Studio sync is slow

- src/containers/MainApp/index.jsx
> fix: remove youtube logo from footer

- package-lock.json
- package.json
- src/components/CourseTable/__snapshots__/CourseTable.test.jsx.snap
- src/components/EditCoursePage/CollapsibleCourseRun.jsx
- src/components/EditCoursePage/EditCourseForm.jsx
- src/components/EditCoursePage/__snapshots__/CollapsibleCourseRun.test.jsx.snap
- src/components/EditCoursePage/__snapshots__/EditCourseForm.test.jsx.snap
- src/components/Header/Header.scss
- src/components/Header/__snapshots__/Header.test.jsx.snap
- src/components/Header/index.jsx
- src/components/TableComponent/__snapshots__/TableComponent.test.jsx.snap
- src/sass/App.scss
Upgrade Paragon, remove edx-bootstrap, and update the prop usage of some components.
> feat: upgrade paragon

- src/components/SidePanes/CommentsPane.jsx
- src/components/SidePanes/CommentsPane.test.jsx
> DISCO-1378: Adds in comment error display

- Makefile
- src/components/CreateCoursePage/CreateCourseForm.jsx
- src/components/CreateCoursePage/__snapshots__/CreateCourseForm.test.jsx.snap
- src/components/CreateCoursePage/index.jsx
- src/components/CreateCourseRunPage/CreateCourseRunForm.jsx
- src/components/CreateCourseRunPage/__snapshots__/CreateCourseRunForm.test.jsx.snap
- src/components/CreateCourseRunPage/index.jsx
- src/components/EditCoursePage/CollapsibleCourseRun.jsx
- src/components/EditCoursePage/CollapsibleCourseRun.test.jsx
- src/components/EditCoursePage/CollapsibleCourseRuns.jsx
- src/components/EditCoursePage/EditCourseForm.jsx
- src/components/EditCoursePage/EditCoursePage.test.jsx
- src/components/EditCoursePage/__snapshots__/CollapsibleCourseRun.test.jsx.snap
- src/components/EditCoursePage/__snapshots__/EditCourseForm.test.jsx.snap
- src/components/EditCoursePage/__snapshots__/EditCoursePage.test.jsx.snap
- src/components/EditCoursePage/index.jsx
- src/data/constants/index.js
- src/data/constants/testData.js
- src/utils/index.js
This field will only be displayed if the selected Course Run Type
has a masters mode slug associated with it.
DISCO-1092
> Adding external key into Publisher UI

- src/components/CourseTable/index.jsx
- src/components/PageContainer/PageContainer.scss
> Remove editors from filtering for staff users

- src/components/CreateCoursePage/CreateCourseForm.jsx
- src/components/CreateCoursePage/__snapshots__/CreateCourseForm.test.jsx.snap
- src/components/CreateCoursePage/index.jsx
- src/components/CreateCourseRunPage/__snapshots__/CreateCourseRunForm.test.jsx.snap
- src/components/CreateCourseRunPage/index.jsx
- src/components/EditCoursePage/EditCourseForm.jsx
- src/components/EditCoursePage/EditCoursePage.test.jsx
- src/components/EditCoursePage/__snapshots__/EditCourseForm.test.jsx.snap
- src/components/EditCoursePage/__snapshots__/EditCoursePage.test.jsx.snap
- src/components/EditCoursePage/index.jsx
- src/components/PriceList/PriceList.test.jsx
- src/components/PriceList/__snapshots__/PriceList.test.jsx.snap
- src/components/PriceList/index.jsx
- src/containers/CreateCourse/CreateCourse.test.jsx
- src/data/constants/testData.js
- src/utils/index.js
https://openedx.atlassian.net/browse/DISCO-1425
> Support multiple prices when using CourseType

- src/utils/index.js
formData.price is undefined if creating an Audit course so
the frontend throws an undefined error.
> Price fix for creating Audit course.

- src/components/CourseTable/__snapshots__/CourseTable.test.jsx.snap
- src/components/CourseTable/index.jsx
https://openedx.atlassian.net/browse/DISCO-1455
Tied to backend PR https://github.com/edx/course-discovery/pull/2302
> Filter on unsubmitted, not unpublished

- src/components/EditCoursePage/EditCourseForm.jsx
- src/components/EditCoursePage/__snapshots__/EditCourseForm.test.jsx.snap
Rather than hiding it completely. A little less surprising for users.
https://openedx.atlassian.net/browse/DISCO-1484
> Disable Add Run button when in review

- src/components/CourseTable/__snapshots__/CourseTable.test.jsx.snap
- src/components/CourseTable/index.jsx
- src/components/Header/__snapshots__/Header.test.jsx.snap
- src/components/Header/index.jsx
https://openedx.atlassian.net/browse/DISCO-1481
> Remove beta branding and warnings

- src/components/CreateCoursePage/CreateCourseForm.jsx
- src/components/CreateCourseRunPage/CreateCourseRunForm.jsx
- src/helpText.jsx
> Update Run Key help text and display optional

- src/components/CourseTable/index.jsx
- src/components/DateTimeField/index.jsx
- src/components/EditCoursePage/CollapsibleCourseRun.jsx
- src/utils/index.js
We were displaying times as UTC, even though we told the user it was in a local timezone. This fixes that.
https://openedx.atlassian.net/browse/DISCO-1518
> Display times in local timezone

- config/webpack.dev.config.js
- config/webpack.prod.config.js
- package-lock.json
- src/components/CourseTable/CourseTable.test.jsx
- src/components/CourseTable/__snapshots__/CourseTable.test.jsx.snap
- src/components/CourseTable/index.jsx
- src/setupTest.js
-remove references to ORG_BLACKLIST config variable
> DISCO-1507 whitelist blacklist cleanup

- src/components/CourseTable/__snapshots__/CourseTable.test.jsx.snap
- src/components/CourseTable/index.jsx
- src/components/TableComponent/__snapshots__/TableComponent.test.jsx.snap
- src/components/TableComponent/index.jsx
- src/containers/CourseDashboard/index.jsx
If the user does not have Publisher permissions, we'll show a more helpful message now (and stop showing interactive bits like a New Course button).
https://openedx.atlassian.net/browse/DISCO-1532
> Be more helpful when user is denied

- package-lock.json
- package.json
- src/components/CreateCoursePage/__snapshots__/CreateCourseForm.test.jsx.snap
- src/components/CreateCourseRunPage/__snapshots__/CreateCourseRunForm.test.jsx.snap
- src/components/EditCoursePage/__snapshots__/CollapsibleCourseRun.test.jsx.snap
- src/setupTest.js
Reverts edx/frontend-app-publisher#381
> Revert "Update dependency tinymce to v5.1.4 [SECURITY]"

- package-lock.json
- package.json
- src/components/CreateCoursePage/__snapshots__/CreateCourseForm.test.jsx.snap
- src/components/CreateCourseRunPage/__snapshots__/CreateCourseRunForm.test.jsx.snap
- src/components/EditCoursePage/__snapshots__/CollapsibleCourseRun.test.jsx.snap
- src/setupTest.js
Reverts edx/frontend-app-publisher#383
> Revert "Revert "Update dependency tinymce to v5.1.4 [SECURITY]""

- Makefile
- README.md
- openedx.yml
> Adding openedx.yml to the repo. Minor updates to Readme

- src/components/CourseTable/index.jsx
- src/components/EditCoursePage/CollapsibleCourseRun.jsx
- src/components/EditCoursePage/EditCourseForm.jsx
- src/components/EditCoursePage/EditCourseForm.test.jsx
- src/components/EditCoursePage/__snapshots__/EditCourseForm.test.jsx.snap
- src/components/StaffList/StaffList.test.jsx
- src/containers/CourseDashboard/index.jsx
- src/containers/CreateCourse/CreateCourse.test.jsx
- src/containers/EditCourse/index.jsx
- src/containers/MainApp/AppTests.test.jsx
- src/data/actions/courseInfo.test.js
- src/data/actions/courseOptions.test.js
- src/data/actions/courseRunOptions.test.js
- src/data/actions/publisherUserInfo.test.js
- src/data/actions/table.test.js
- src/data/reducers/index.js
- src/data/services/DiscoveryDataApiService.test.js
- src/setupTest.js
Switch to calling getAuthenticatedUser rather than keeping the auth value in the store. This was something that broke when switching to frontend-platform.
https://openedx.atlassian.net/browse/DISCO-1598
> Use frontend-platform/auth correctly

- public/index.html
This changed with HtmlWebpackPlugin 4
> Fix template variable syntax

- src/components/Collaborator/index.jsx
- src/components/Collaborator/renderSuggestion.jsx
- src/components/CollaboratorPage/CollaboratorForm.jsx
> WS-1258 update collab image size

- README.md
This adds a README section summarizing what Publisher does, with an emphasis on who might get the most use out of it.
> When to use Publisher?

- src/utils/index.js
> WS-1293: Gracefully handle Collaborators who are missing names or images.

- src/components/EditCoursePage/CollapsibleCourseRun.jsx
- src/components/EditCoursePage/EditCourseForm.jsx
- src/components/EditCoursePage/__snapshots__/EditCourseForm.test.jsx.snap
> WS-1383: add course preview links to publisher

- package-lock.json
- package.json
add brand package in dependencies.
VAN-233
> Add brand package

- package-lock.json
- package.json
- src/components/EditCoursePage/EditCoursePage.test.jsx
- src/components/Header/__snapshots__/Header.test.jsx.snap
- src/components/TableComponent/__snapshots__/TableComponent.test.jsx.snap
- src/sass/App.scss
Add brand package and update its relevant imports.
VAN-233
> update imports from brand package

- package-lock.json
- package.json
- src/components/CourseTable/__snapshots__/CourseTable.test.jsx.snap
- src/components/Header/__snapshots__/Header.test.jsx.snap
- src/components/ListField/__snapshots__/ListField.test.jsx.snap
- src/components/ListField/index.jsx
> chore: upgrade deps

- package-lock.json
- package.json
Reverts openedx/frontend-app-publisher#643
> Revert "fix(deps): update dependency history to v5"

- src/utils/validation.js
- src/utils/validation.test.js
Update staff requirement check as in #662 after update in track name.
[PROD-2745](https://openedx.atlassian.net/browse/PROD-2745)
> refactor: update price field name for staff check

- package-lock.json
- package.json
Reverts openedx/frontend-app-publisher#673
> Revert "fix(deps): update dependency @tinymce/tinymce-react to v3.13.1"

- renovate.json
Latest versions has some breaking changes.
> chore: add constraint for tinymce-react to 3.10.4

- package-lock.json
- package.json
- src/components/CourseTable/__snapshots__/CourseTable.test.jsx.snap
- Update paragon to the latest version
- Fix UI issues, if any, after the update
- Update the snapshot tests
- The SearchField on CourseTable was updated in paragon recently under https://github.com/openedx/paragon/pull/1158 and that's why its snapshot tests are updated  
- Test the UI and Responsiveness(Tested on Chrome and Safari)
> chore: update paragon

- src/components/Header/__snapshots__/Header.test.jsx.snap
- src/components/Header/index.jsx
- Change logo url to reference Publisher base url instead of studio url
- Update user dropdown styling to match other MFEs headers
- Snapshots updated as a result of changes
> chore: header updates

- package-lock.json
- package.json
- src/components/EditCoursePage/__snapshots__/EditCoursePage.test.jsx.snap
- src/components/EditCoursePage/index.jsx
- src/components/SidePanes/CatalogInclusionPane.jsx
- src/components/SidePanes/CatalogInclusionPane.test.jsx
- src/components/SidePanes/Pane.jsx
- src/components/SidePanes/index.jsx
https://2u-internal.atlassian.net/browse/ENT-5834
Add behavior to toggle the Subscription Catalog inclusion boolean. This behavior should only be shown when the user has is_staff = true permissions. This also includes the work with the backend functionality of the metadata updating. This endpoint should ensure on the backend that they are staff for security purposes.
**Screenshot with info hover**
**Error state**
> feat: Create a Course Pane for Subscription Toggle

- src/components/EditCoursePage/AdditionalMetadataFields.jsx
- src/components/EditCoursePage/EditCoursePage.test.jsx
- src/components/EditCoursePage/__snapshots__/AdditionalMetadataFields.test.jsx.snap
- src/components/EditCoursePage/__snapshots__/EditCoursePage.test.jsx.snap
- src/components/EditCoursePage/index.jsx
I need to make the field less strict on the discovery side as well. Reverting to unblock others.
Reverts openedx/frontend-app-publisher#765
> Revert "feat: add variant_id to publisher UI for exec ed courses"

- src/components/EditCoursePage/EditCourseForm.jsx
- src/components/EditCoursePage/__snapshots__/EditCourseForm.test.jsx.snap
Small copy edit to clarify that location restriction is for merchandising only.
Internal ticket: https://2u-internal.atlassian.net/browse/WS-3375
> fix: add "Merchandising" to location restriction heading

- decisions/0002-new-instructor-org-association.rst
- decisions/0003-publisher-access-restriction.rst
- ADR for publisher access restriction for internal users.
- Discovery ADR: https://github.com/openedx/course-discovery/pull/3657
> docs: internal users access restriction ADR

- src/components/EditCoursePage/AdditionalMetadataFields.jsx
- src/components/EditCoursePage/__snapshots__/AdditionalMetadataFields.test.jsx.snap
https://2u-internal.atlassian.net/browse/WS-3010
Frontend change for the publisher, add a new field for additional information, and course term override.
> feat: Add new course term in publisher.

- package-lock.json
- package.json
- src/components/CourseTable/__snapshots__/CourseTable.test.jsx.snap
- src/components/CreateCoursePage/__snapshots__/CreateCoursePage.test.jsx.snap
- src/components/CreateCourseRunPage/__snapshots__/CreateCourseRunPage.test.jsx.snap
- src/components/EditCoursePage/__snapshots__/EditCoursePage.test.jsx.snap
- src/components/EditCoursePage/__snapshots__/TranscriptLanguage.test.jsx.snap
- src/components/Header/__snapshots__/Header.test.jsx.snap
- src/components/ImageUpload/__snapshots__/ImageUpload.test.jsx.snap
- src/components/ListField/__snapshots__/ListField.test.jsx.snap
- src/components/RenderInputTextField/__snapshots__/RenderInputTextField.test.jsx.snap
- src/components/RenderSelectField/__snapshots__/RenderSelectField.test.jsx.snap
- src/components/StafferPage/__snapshots__/StafferPage.test.jsx.snap
- src/components/TableComponent/__snapshots__/TableComponent.test.jsx.snap
- src/index.jsx
Major version upgrade of `edx/paragon`.
> build: major paragon version upgrade

- decisions/0004-product-source-field.rst
> feat: add product source ADR

- src/components/CreateCoursePage/CreateCourseForm.jsx
- src/components/CreateCoursePage/__snapshots__/CreateCourseForm.test.jsx.snap
- src/components/RenderSelectField/__snapshots__/RenderSelectField.test.jsx.snap
- src/components/RenderSelectField/index.jsx
Desc:
- Remove default param from RenderSelectField
> fix: remove default param from RenderSelect field

- decisions/0005-product-source-based-required-fields.rst
This PR adds the ADR for AdditionalMetadata fields validation
> feat: add ADR for AdditionalMetadata fields validation

- src/components/CreateCoursePage/CreateCourseForm.jsx
- src/components/CreateCoursePage/CreateCourseForm.scss
- src/components/CreateCoursePage/__snapshots__/CreateCourseForm.test.jsx.snap
- src/components/CreateCoursePage/__snapshots__/CreateCoursePage.test.jsx.snap
- src/components/CreateCoursePage/index.jsx
- src/components/ReduxFormCreatableSelect/index.jsx
- src/components/StafferPage/StafferForm.jsx
- src/components/StafferPage/__snapshots__/StafferForm.test.jsx.snap
- src/utils/validation.js
This PR changes the organization selector in create course form to be searchable.
> feat: make organization dropdown searchable

- src/components/EditCoursePage/EditCourseForm.jsx
- src/components/EditCoursePage/EditCourseForm.test.jsx
- src/components/EditCoursePage/__snapshots__/EditCourseForm.test.jsx.snap
- src/helpText.jsx
- src/helpText.test.jsx
[PROD-3461](https://2u-internal.atlassian.net/browse/PROD-3461)
------------------
This PR updates help text for `URL Slug` field based on `IS_NEW_SLUG_FORMAT_ENABLED` value
**with `IS_NEW_SLUG_FORMAT_ENABLED = 'false'`**
**with `IS_NEW_SLUG_FORMAT_ENABLED = 'true'`**
> chore: update help text update for url slug field

- package-lock.json
- package.json
Downgrade `@tinymce/tinymce-react`
> build: downgrade @tinymce/tinymce-react

- package-lock.json
- package.json
Adds the missing atlas package for new pull translation.
> chore: add atlas in package.json

- src/components/EditCoursePage/__snapshots__/CollapsibleCourseRun.test.jsx.snap
- src/data/actions/courseInfo.js
- src/data/actions/courseInfo.test.js
Update the save button state in case of editing the certificate heading or description.
PROD-3419
> feat: update save button state for certificate info

- catalog-info.yaml
https://open-edx-proposals.readthedocs.io/en/latest/processes/oep-0055/decisions/0001-use-backstage-to-support-maintainers.html
> docs: add catalog-info.yaml

- src/components/DateTimeField/index.jsx
> fix: update default time from 12:00 to 00:00

- src/components/EditCoursePage/__snapshots__/CollapsibleCourseRun.test.jsx.snap
- src/components/Header/__snapshots__/Header.test.jsx.snap
- src/components/Header/index.jsx
- src/data/constants/index.js
- src/helpText.jsx
- src/setupTest.js
- src/utils/index.js
- src/utils/utils.test.js
Removes any bootcamp references.
> chore: remove bootcamps

- README.md
- src/components/CreateCoursePage/CreateCourseForm.jsx
- src/components/CreateCoursePage/__snapshots__/CreateCourseForm.test.jsx.snap
- src/components/CreateCourseRunPage/__snapshots__/CreateCourseRunForm.test.jsx.snap
- src/components/EditCoursePage/EditCourseForm.jsx
- src/components/EditCoursePage/__snapshots__/CollapsibleCourseRun.test.jsx.snap
- src/components/EditCoursePage/__snapshots__/EditCourseForm.test.jsx.snap
- src/helpText.jsx
Ref https://github.com/openedx/docs.openedx.org/issues/955
> docs: Update edx.rtd.io links to docs.openedx.org

- package-lock.json
- package.json
This PR aims to remove the edx footer reference and replace it with the default openedx footer for community friendly. 
- https://github.com/openedx/frontend-app-publisher/issues/1004
> fix: reference openedx footer

- decisions/0007-bulk-operations.rst
Add an ADR for bulk operations via CSV uploads
> docs: add bulk operations ADR

- package-lock.json
- package.json
- src/components/BulkOperationDetailsPage/BulkOperationDetails.jsx
- src/components/BulkOperationDetailsPage/BulkOperationDetails.test.jsx
- src/components/BulkOperationDetailsPage/index.jsx
- src/components/BulkOperationDetailsPage/styles.scss
- src/containers/MainApp/index.jsx
- src/data/services/DiscoveryDataApiService.js
- src/data/services/DiscoveryDataApiService.test.js
- src/utils/index.js
- src/utils/utils.test.js
[PROD-4368](https://2u-internal.atlassian.net/browse/PROD-4368)
-----------
This PR adds the `Bulk Operation Task Details` page, which displays detailed attributes for a single record
https://github.com/user-attachments/assets/d06cba96-1826-4974-90c2-0e366d9495ad
> feat: Bulk Operation Task Details Page
