config/webpack.common.config.js
public/index.html

The <base> change is not strictly required. I think firefox was able to determine what we were trying to say regardless. But figured this is more compliant.

Fix nested path URLs not finding webfonts

---

config/webpack.dev.config.js
config/webpack.prod.config.js
package-lock.json
package.json
src/components/LabelledData/LabelledData.test.jsx
src/components/LabelledData/__snapshots__/LabelledData.test.jsx.snap
src/components/LabelledData/index.jsx
src/containers/CourseView/CourseView.test.jsx
src/containers/CourseView/index.jsx
src/data/actions/courseInfo.js
src/data/actions/courseInfo.test.js
src/data/constants/courseInfo.js
src/data/reducers/courseInfo.js
src/data/reducers/courseInfo.test.js
src/data/reducers/index.js
src/data/services/DiscoveryDataApiService.js
src/index.jsx
src/setupTest.js

This adds a simple read-only view of a given course.
Adds courses/<uuid> route.
It looks like crap right now. But that can be fixed up later.
Normal view:
Error screen:
Spinner while data loads:

Add CourseView route and view

---

src/data/services/DiscoveryDataApiService.js

This will ensure that we get the draft data back, if available. And will confirm that editor permissions are respected. It also protects against 404s if no non-draft version exists.

Ask for editable versions whenever we query courses

---

src/components/EditCoursePage/index.jsx

Figured out why the incomplete pill wasn't always showing up. Shouldn't be using `!!`

Fix course status pill for when there are incomplete runs

---

src/components/EditCoursePage/CollapsibleCourseRun.jsx
src/components/EditCoursePage/CollapsibleCourseRun.test.jsx
src/components/EditCoursePage/CollapsibleCourseRuns.jsx
src/components/EditCoursePage/EditCourseForm.jsx
src/components/EditCoursePage/EditCoursePage.test.jsx
src/components/EditCoursePage/TranscriptLanguage.jsx
src/components/EditCoursePage/TranscriptLanguage.test.jsx
src/components/EditCoursePage/__snapshots__/CollapsibleCourseRun.test.jsx.snap
src/components/EditCoursePage/__snapshots__/EditCourseForm.test.jsx.snap
src/components/EditCoursePage/__snapshots__/EditCoursePage.test.jsx.snap
src/components/EditCoursePage/__snapshots__/TranscriptLanguage.test.jsx.snap
src/components/EditCoursePage/index.jsx
src/components/RichEditor/__snapshots__/RichEditor.test.jsx.snap
src/components/RichEditor/index.jsx
src/components/StaffList/StaffList.test.jsx
src/components/StaffList/__snapshots__/StaffList.test.jsx.snap
src/components/StaffList/index.jsx
src/components/StafferPage/StafferForm.jsx
src/components/StafferPage/StafferForm.test.jsx
src/containers/EditCourse/index.jsx
src/data/actions/courseSubmitInfo.js
src/data/actions/courseSubmitInfo.test.js
src/data/constants/courseSubmitInfo.js
src/data/reducers/courseSubmitInfo.js
src/data/reducers/courseSubmitInfo.test.js
src/data/reducers/index.js
src/utils/index.js
src/utils/utils.test.js
src/utils/validation.js
src/utils/validation.test.js

DISCO-878
Note: we don't pass through props on fields within field arrays which rely on `meta` to avoid "polluting" the field meta info with higher up meta information

Client side validation/focus for non-input fields

---

src/components/StafferPage/StafferForm.jsx
src/components/StafferPage/__snapshots__/StafferForm.test.jsx.snap

Oops. The "institution" is now "organization" to be more inline with the language elsewhere. The screenshot is a little dated.

Adding tooltips to the instructor create/edit page

---

src/components/EditCoursePage/EditCourseForm.jsx
src/components/EditCoursePage/__snapshots__/EditCourseForm.test.jsx.snap
src/data/actions/courseSubmitInfo.js
src/data/actions/courseSubmitInfo.test.js
src/data/reducers/courseSubmitInfo.js
src/data/reducers/courseSubmitInfo.test.js
src/utils/validation.js

Our custom error validation was getting in the way of some fields being able to open the collapsible to focus the field in error.
This fixes that by stopping validation in an error case and having the edit course form notice.
Stopping validation also prevents the submit button from spinning forever.
https://openedx.atlassian.net/browse/DISCO-972
https://openedx.atlassian.net/browse/DISCO-973
I also opened https://openedx.atlassian.net/browse/DISCO-992 to deal with the setTimeout call that I'm lazily introducing.

Open collapsible after custom error validation

---

src/components/EditCoursePage/CollapsibleCourseRun.jsx

Users can change their course run start dates to
today or later, unless their start date has already
passed. In the latter case, they can change the start
date to the initially set start date or later (this may
result in changing a start date to a date in the past,
which is a small use case).
DISCO-1135

Start Date bug

---

src/components/EditCoursePage/CollapsibleCourseRun.jsx
src/components/EditCoursePage/CollapsibleCourseRun.test.jsx
src/components/EditCoursePage/EditCourseForm.jsx
src/components/EditCoursePage/EditCourseForm.test.jsx
src/components/EditCoursePage/EditCoursePage.test.jsx
src/components/EditCoursePage/__snapshots__/CollapsibleCourseRun.test.jsx.snap
src/components/EditCoursePage/__snapshots__/EditCourseForm.test.jsx.snap
src/components/EditCoursePage/__snapshots__/EditCoursePage.test.jsx.snap
src/components/EditCoursePage/index.jsx
src/components/ImageUpload/__snapshots__/ImageUpload.test.jsx.snap
src/components/ImageUpload/index.jsx
src/containers/EditCourse/index.jsx
src/data/actions/courseOptions.js
src/data/actions/courseOptions.test.js
src/data/reducers/courseOptions.test.js
src/data/services/DiscoveryDataApiService.js

* Ask for OPTIONS on the list-courses endpoint, not a specific course endpoint - because the backend will refuse an OPTIONS for a specific course if you can't PUT to it.
* Support the new `editable` serialized field and disable all fields / hide buttons when it is `false` 
https://openedx.atlassian.net/browse/DISCO-1143

Support viewing courses we can't edit

---

src/components/CreateCourseRunPage/CreateCourseRunPage.test.jsx
src/components/CreateCourseRunPage/__snapshots__/CreateCourseRunPage.test.jsx.snap
src/components/CreateCourseRunPage/index.jsx

If a course is under review, don't allow the workaround of manually editing the URL field and putting in /rerun to still get the form.
Now you'll see a little warning page instead explaining that you can't add new runs.
https://openedx.atlassian.net/browse/DISCO-894

Disallow adding new runs when in review

---

src/components/EditCoursePage/EditCourseForm.jsx
src/components/EditCoursePage/__snapshots__/EditCourseForm.test.jsx.snap

Stop passing down a validate method for the whole form down to the
field array of runs. This method was causing a false positive on
errors being present.

Avoid submission nested error loops

---

renovate.json

Going to let some package dependency upgrade PRs generate, then go back to the early Monday schedule

Temporarily remove renovate schedule

---

src/components/CourseTable/__snapshots__/CourseTable.test.jsx.snap
src/components/CourseTable/index.jsx
src/components/EditCoursePage/index.jsx
src/data/services/DiscoveryDataApiService.js

Whenever we show the course number, prefer key_for_reruns, as that is what the course team member is going to be thinking of as their key.
This doesn't change how we use course keys, just how we display them.
https://openedx.atlassian.net/browse/DISCO-1358

Prefer key_for_reruns as course number

---

src/components/EditCoursePage/CollapsibleCourseRun.jsx
src/components/EditCoursePage/EditCoursePage.test.jsx
src/components/EditCoursePage/__snapshots__/EditCoursePage.test.jsx.snap
src/components/EditCoursePage/index.jsx
src/data/actions/courseInfo.js
src/utils/index.js

To prevent load on discovery, help with requests/min, and help avoid
deadlock. This will look for course runs that were changed
as well as saving non-archived course runs if the course mode or price
changed.

DISCO-1371: Only save course runs that changed

---

package-lock.json
package.json
src/components/EditCoursePage/index.jsx
src/utils/index.js

Add dependency on fast-json-stable-stringify (it was already in our dependency tree) to deterministically compare objects.
Hopefully will fix us accidentally sending too many course runs when saving and hitting deadlocks.

Compare objects with stable stringify

---

src/components/EditCoursePage/EditCoursePage.test.jsx
src/components/EditCoursePage/index.jsx
src/data/actions/courseInfo.js

This will avoid an unnecessary error when PCs and Legal submit internal reviews.

Avoid calling forEach on an object

---

package-lock.json
package.json
src/components/CourseTable/__snapshots__/CourseTable.test.jsx.snap
src/components/EditCoursePage/CollapsibleCourseRun.jsx
src/components/EditCoursePage/EditCourseForm.jsx
src/components/EditCoursePage/__snapshots__/CollapsibleCourseRun.test.jsx.snap
src/components/EditCoursePage/__snapshots__/EditCourseForm.test.jsx.snap
src/components/Header/Header.scss
src/components/Header/__snapshots__/Header.test.jsx.snap
src/components/Header/index.jsx
src/components/TableComponent/__snapshots__/TableComponent.test.jsx.snap
src/sass/App.scss

Reverts edx/frontend-app-publisher#313
We have noticed that with this change, frontend validation has stopped working since when any collapsible is closed, all of the Fields inside of it are unregistered. This means it is possible to make submissions that get around any frontend validation simply by closing the collapsible.

Revert "feat: upgrade paragon"

---

src/components/RichEditor/__snapshots__/RichEditor.test.jsx.snap
src/components/RichEditor/index.jsx

Diacritic characters get represented as html entities without this set, so setting this allows our backend to receive them as is and thus won't break in our `clean_html` method.

DISCO-1431: Uses raw encoding for fields in TinyMCE

---

src/components/EditCoursePage/CollapsibleCourseRun.jsx

As a way to support legacy course runs that have seats that do not
match with anything currently supported, we allow course run types
that do not exist under a course type (a mismatch). This will ensure
the frontend continues to behave nicely

Handle unknown run types that are caused from mismatches

---

config/webpack.dev.config.js
config/webpack.prod.config.js
src/components/CreateCoursePage/CreateCourseForm.jsx
src/components/CreateCoursePage/CreateCourseForm.test.jsx
src/components/CreateCoursePage/CreateCoursePage.test.jsx
src/components/CreateCoursePage/__snapshots__/CreateCourseForm.test.jsx.snap
src/components/CreateCoursePage/__snapshots__/CreateCoursePage.test.jsx.snap
src/components/CreateCoursePage/index.jsx
src/containers/CreateCourse/CreateCourse.test.jsx
src/setupTest.js

We're confident enough now in CourseType and friends to turn it on for all newly created courses.
Note that edit pages still support courses without types.
https://openedx.atlassian.net/browse/DISCO-1497

Drop TYPE_WHITELIST

---

src/components/CreateCourseRunPage/__snapshots__/CreateCourseRunPage.test.jsx.snap
src/components/CreateCourseRunPage/index.jsx
src/data/actions/courseInfo.js

As a stop-gap measure, we give a special message when receiving a 504 message back from Discovery when making a rerun.
I didn't add a test, because we still don't seem to have a good way to test network interactions. Seems bad, yah?
https://openedx.atlassian.net/browse/DISCO-1548

Add a special 504 message on reruns

---

src/data/actions/courseInfo.js

When checking for a 504 response for reruns, also handle an undefined response as a 504 (which is what happens in stage/prod).
https://openedx.atlassian.net/browse/DISCO-1548

Handle no response in 504 message

---

src/components/EditCoursePage/CollapsibleCourseRun.jsx
src/components/EditCoursePage/EditCourseForm.jsx

Instead of showing a white page because of a JS exception, simply treat it as an unset type. Which also allows the user to change it.
https://openedx.atlassian.net/browse/DISCO-1581

Handle the Empty course/run type better

---

src/components/CourseTable/index.jsx

It reversed a conditional, which made the dashboard filtering on course statuses behave oddly.  Whoops.

Fix a typo in the previous commit

---

renovate.json

That was an old config we can drop now.

Don't ignore babel-loader in renovate

---

package-lock.json
package.json

v3 and above require a newer version of git than we have on our builders.

Whoops, downgrade husky to v2

---

src/components/EditCoursePage/CollapsibleCourseRun.jsx
src/components/EditCoursePage/CollapsibleCourseRun.test.jsx
src/components/EditCoursePage/CourseButtonToolbar.jsx
src/components/EditCoursePage/CourseRunButtonToolbar.jsx
src/components/EditCoursePage/CourseRunButtonToolbar.test.jsx
src/components/EditCoursePage/CourseRunSubmitButton.jsx
src/components/EditCoursePage/CourseRunSubmitButton.test.jsx
src/components/EditCoursePage/EditCourseForm.jsx
src/components/EditCoursePage/EditCoursePage.test.jsx
src/components/EditCoursePage/__snapshots__/CollapsibleCourseRun.test.jsx.snap
src/components/EditCoursePage/__snapshots__/CourseRunButtonToolbar.test.jsx.snap
src/components/EditCoursePage/__snapshots__/CourseRunSubmitButton.test.jsx.snap
src/components/EditCoursePage/__snapshots__/EditCourseForm.test.jsx.snap
src/components/EditCoursePage/index.jsx

That is, when the Save button is pressed, if there are changes to an existing published run, we'll republish it automatically.
This also removes the button to specifically republish a single run.
Hopefully this will avoid users queuing up draft changes and not realizing they aren't published.
https://openedx.atlassian.net/browse/DISCO-1555

Re-publish runs by default on Save

---

package-lock.json
package.json

5.3.0 breaks our usage of tinymce, and I don't have time right now to investigate what the proper fix is.

Downgrade tinymce to 5.2.2

---

package-lock.json
package.json
src/components/RichEditor/index.jsx

Updated `tinymce-language-selector` to point to an npm package owned by edX, rather than our own repo.
(FYI: Our internal [tinymce-language-selector](https://github.com/edx/tinymce-language-selector) repo was updated to use [semantic-release](https://github.com/semantic-release/semantic-release) to release versions to [@edx/tinymce-language-selector](https://www.npmjs.com/package/@edx/tinymce-language-selector) on npm. Another `tinymce-language-selector` npm package based on our internal repo exists, however, it is not owned by our org so we cannot release new features/fixes to it.)

DISCO-1586: Fix tinymce-language-selector error

---

jest.config.js
webpack.dev.config.js
webpack.prod.config.js

Removed `tinymce-language-selector` from webpack.dev.config.js,
webpack.prod.config.js, and jest.config.js. Ignoring this package
is now covered by the `@edx` in the webpack files.
DISCO-1586

Cleanup webpack and jest config

---

src/components/CreateCoursePage/CreateCourseForm.jsx
src/components/EditCoursePage/CollapsibleCourseRun.jsx
src/components/EditCoursePage/EditCoursePage.test.jsx
src/components/EditCoursePage/__snapshots__/CollapsibleCourseRun.test.jsx.snap
src/components/EditCoursePage/__snapshots__/EditCoursePage.test.jsx.snap
src/components/EditCoursePage/index.jsx

- add upgrade deadline date field in course run form.
- Only staff user can edit this field.
This PR is dependent on 
https://github.com/edx/course-discovery/pull/3123/
DISCO-1622

fix: add upgrade deadline override field

---

src/components/EditCoursePage/index.jsx

- due to undefined upgrade_deadlin_override some courses were not loading
DISCO-1777

fix:some courses not loading

---

src/utils/validation.js
src/utils/validation.test.js

This PR will add a check to make `staff` field optional for `Executive Education` courses. 
[PROD-2685](https://openedx.atlassian.net/browse/PROD-2685)
Validation function only receive track `type`'s uuid (as in disco) under `targetRun` prop therefore I can't seem to find an easier way to determine track type name in validation function. One option is to take `mode` from `entitlement` prop but that only works if correct track is set at creation (e.g. not if we are editing from Audit to Executive Education). Hence, this `prices.<track-slug>` field only have a positive count when desired track (i.e. executive education) is selected. However, if there are better options available, we should opt that or make sure that the underlying assumption is correct before merging this PR.

feat: make staff optional for exec ed courses

---

src/components/CourseTable/__snapshots__/CourseTable.test.jsx.snap
src/components/CourseTable/index.jsx
src/components/TableComponent/TableComponent.scss
src/components/TableComponent/TableComponent.test.jsx
src/components/TableComponent/__snapshots__/TableComponent.test.jsx.snap
src/components/TableComponent/index.jsx
src/containers/TableContainer/index.jsx

Part 1 of replacing the Course listing table in publisher with Paragon's data table. The changes in this PR:
- Replacement of Table with DataTable
- Change cell width to fix header-data misalignment
- Make the height of the table auto instead of fixed height
- Keep sorting on title and course key
The follow-up PR will focus on using table filters and showing empty status from the data table instead of the existing error messsage. 
- https://paragon-openedx.netlify.app/components/datatable/
- https://react-table.tanstack.com/docs/api/useTable

feat: updating table to data table

---

src/components/LoadingSpinner/__snapshots__/LoadingSpinner.test.jsx.snap
src/components/LoadingSpinner/index.jsx
src/components/TableComponent/TableComponent.scss
src/components/TableComponent/__snapshots__/TableComponent.test.jsx.snap
src/components/TableComponent/index.jsx

- Let DataTable handle no data found/empty state
- Use paragon [spinner component](https://paragon-openedx.netlify.app/components/spinner/) in loading spinner
- Word break table data to avoid overflows

feat: data table updates

---

src/components/EditCoursePage/AdditionalMetadataFields.jsx
src/components/EditCoursePage/AdditionalMetadataFields.test.jsx
src/components/EditCoursePage/EditCourseForm.jsx
src/components/EditCoursePage/EditCoursePage.test.jsx
src/components/EditCoursePage/__snapshots__/AdditionalMetadataFields.test.jsx.snap
src/components/EditCoursePage/__snapshots__/EditCoursePage.test.jsx.snap
src/components/EditCoursePage/index.jsx
src/data/constants/index.js

[handle additionalMetadata model on publisher for ExEd courses](https://openedx.atlassian.net/browse/PROD-2711)
Add fields to input additonal Metadata fields for executive educations courses only

feat: Add fields for additional meta data in course edit form

---

src/components/CourseTable/index.jsx
src/components/Header/Header.scss
src/components/Header/__snapshots__/Header.test.jsx.snap
src/components/Header/index.jsx
src/utils/index.js

This PR will add navigation routes to different course filters. 
[PROD-2780](https://openedx.atlassian.net/browse/PROD-2780)
Existing implementation for query parameters handling in course tables page is little tricky. It caters filters and search side by side and some utility functions are naive e.g. filtering of `selectedFilters` from component state while updating url. In order to work with existing implementation and not break them, this solution has been added this way. This could be improved along with updating logic for handling existing query parameters and filters.

feat: add navigation to course groups

---

src/components/EditCoursePage/AdditionalMetadataFields.jsx
src/components/EditCoursePage/EditCoursePage.test.jsx
src/components/EditCoursePage/__snapshots__/AdditionalMetadataFields.test.jsx.snap
src/components/EditCoursePage/__snapshots__/EditCoursePage.test.jsx.snap
src/components/EditCoursePage/index.jsx

This PR adds `start_date` and `registration_deadline` fields in Course Edit form under Additional Metadata.
[PROD-2864](https://2u-internal.atlassian.net/browse/PROD-2864)
1. Checkout latest master from openedx/course-discovery and apply migrations
2. Checkout this branch
3. Edit course input dates in new fields
4. Verify from db/api if they are added in related course
5. Verify from UI that the values are reflected in form

feat: add start_date and registration_deadline in AdditionoalMetadata

---

.stylelintrc
package-lock.json
package.json

###[ PROD-2872](https://2u-internal.atlassian.net/browse/PROD-2872)
replaced stylelint-declaration-use-variable with stylelint-declaration-strict-value to resolve the stylelint dep conflict issue. [styleline-declaration-use-variable](https://github.com/sh-waqar/stylelint-declaration-use-variable) is no longer supported. Their readme page is suggesting to use [stylelint-declaration-strict-value](https://github.com/AndyOGo/stylelint-declaration-strict-value)

build: remove outdated package and use alternative to fix dep issue

---

src/components/EditCoursePage/AdditionalMetadataFields.jsx
src/components/EditCoursePage/EditCoursePage.test.jsx
src/components/EditCoursePage/__snapshots__/AdditionalMetadataFields.test.jsx.snap
src/components/EditCoursePage/__snapshots__/EditCoursePage.test.jsx.snap
src/components/EditCoursePage/index.jsx

Add variant_id to publisher UI, now that it exists as a field within the discovery service

feat: add variant_id to publisher UI for exec ed courses

---

src/components/RichEditor/__snapshots__/RichEditor.test.jsx.snap
src/components/RichEditor/index.jsx

Fix the loading of content and skin css files for tinymce editor. The incorrect import was causing styles to not apply as expected, causing issues for dialog/pop-up behavior.
- https://github.com/openedx/frontend-app-discussions/blob/b15fd961085d987157ea15001a0b8e504c7a4dc7/src/components/TinyMCEEditor.jsx
- https://www.tiny.cloud/docs/advanced/usage-with-module-loaders/webpack/webpack_es6_npm/
- https://www.tiny.cloud/docs/advanced/usage-with-module-loaders/reference/content-css/
- https://www.tiny.cloud/docs-3x/reference/Configuration3x/Configuration3x@content_css/
- Run publisher on your local on master.
- Run npm install to have updated reqs
- Open any course for editing. Try edit link or change browser default language for any markdown editor field
- You will notice the issue as …

fix: tinymce css loading fixup

---

src/components/CreateCourseRunPage/__snapshots__/CreateCourseRunPage.test.jsx.snap
src/components/EditCoursePage/EditCourseForm.jsx
src/components/EditCoursePage/EditCourseForm.test.jsx
src/components/EditCoursePage/EditCoursePage.test.jsx
src/components/EditCoursePage/__snapshots__/EditCourseForm.test.jsx.snap
src/components/EditCoursePage/__snapshots__/EditCoursePage.test.jsx.snap
src/components/EditCoursePage/index.jsx
src/components/RenderSelectField/updated-paragon-component.jsx
src/data/constants/testData.js

This PR adds the location restriction fields `restriction_type`, `countries` and `states`. All field options come from course discovery.
These fields specify the regions for which a course will be made available.
~~
Note: I pulled in the most up-to-date react select component to use for these new fields. This is because the existing InputSelect doesn't have a multiselect option.  I had made a PR to add multiselect functionality to InputSelect but realized that we will be moving off InputSelect in Publisher soon.
So this PR puts the code in an interim state where there are *two* versions of the select component - the soon-to-be-deprecated InputSelect that we are using across Publisher and a new paragon component that I've added for the location restriction fields only. However [this …

WS-3120: add location restriction fields

---

src/components/Header/Header.scss
src/components/Header/__snapshots__/Header.test.jsx.snap
src/components/Header/index.jsx
src/components/ListField/ListField.scss
src/components/ListField/__snapshots__/ListField.test.jsx.snap
src/components/ListField/index.jsx

Reduces the amount of SCSS in the repo, by applying the styling using bootstrap classes wherever possible.
The main goal is to reduce number of instances where bootstrap variables are used in custom styles, and replace them by applying bootstrap classes directly on the elements. E.g. removing style `color: $gray-300;`, and adding `text-gray-300` class to disabled links in the header.
The secondary goals are to remove unused styles (i.e. styles that don't have any effect) and remove custom styles that can be replaced by bootstrap classes.
* Setup local `master` devstack
* Checkout the branch in `frontend-app-publisher`
* Run `make frontend-app-publisher-up studio-up` to spin up necessary containers
* Go to `localhost:18000` and sign in
* Go to `localhost:18400`
* Create a new course
* From …

refactor: reduce SCSS

---

src/components/EditCoursePage/EditCourseForm.jsx
src/components/EditCoursePage/__snapshots__/EditCourseForm.test.jsx.snap

Changing the Emsi name to Lightcast in Skills tooltip because now Emsi is branded as Lightcast. 
Jira: [ENT-6287](https://2u-internal.atlassian.net/browse/ENT-6287)

chore: change Emsi to Lightcast in Skills tooltip

---

src/components/StafferPage/StafferForm.jsx
src/components/StafferPage/__snapshots__/StafferForm.test.jsx.snap

[PROD-3052](https://2u-internal.atlassian.net/browse/PROD-3052)
This PR is created by @AfaqShuaib09 but due to urgency of deliveries and delays of CLA, I am authoring this PR. 
This should close #808 and #807 
This PR increases the character limit for the course instructor's bio to 1000 characters.
As there is no limit on the backend for the bio field nor in the serializer, this change is only related to the front end.
Testing instructions:
- Create a people object from the discovery admin.
- Run the frontend-app-publisher locally.
- Visit the localhost:18400/instructors/{people.uuid} page.
> uuid is the uuid of the people object created in the first step.
- Verify that the bio field has a character limit of 1000.
Screenshot:

fix: change staff bio length from 250 to 1000 characters

---

.env.development
src/components/CourseTable/CourseTable.scss
src/components/CourseTable/__snapshots__/CourseTable.test.jsx.snap
src/components/CourseTable/index.jsx
src/components/EditCoursePage/CollapsibleCourseRun.jsx
src/components/EditCoursePage/EditCourseForm.jsx
src/components/EditCoursePage/__snapshots__/CollapsibleCourseRun.test.jsx.snap
src/components/EditCoursePage/__snapshots__/EditCourseForm.test.jsx.snap
src/components/FieldHelp/index.jsx
src/components/FieldLabel/index.jsx
src/components/RemoveButton/__snapshots__/RemoveButton.test.jsx.snap
src/components/RemoveButton/index.jsx
src/components/SidePanes/Pane.jsx
src/components/SidePanes/User.jsx
src/components/SidePanes/UsersPane.jsx
src/components/SidePanes/UsersPane.test.jsx
src/components/Staffer/__snapshots__/Staffer.test.jsx.snap
src/components/Staffer/index.jsx
src/containers/MainApp/AppTests.test.jsx

In this PR, we make some small UI changes in publisher. In particular, the changes introduced are as follows:-
- Fix logo link to redirect to publisher home page
- Use sentence case for course table headings and New Course button
- Shift new course button towards the right of the page
- Remove lock icon for in-review courses
- Change font-color at a few places
- Updating a few icons to those from @edx/paragon
- Update Form Labels for Optional fields
1. On the publisher landing page : -
- Verify that the New Course Button and Table Headings are in sentence case
- Verify that the New Course Button occurs on the far right of the page
- Verify that in the Courses Table, in-review courses no longer have a lock icon displayed in the States column
- Verify that clicking on the logo on the …

refactor: minor UI updates

---

src/components/CourseTags/fetchCourseTagSuggestions.jsx
src/components/CourseTags/renderCourseTagSuggestion.jsx
src/components/EditCoursePage/EditCourseForm.jsx
src/components/EditCoursePage/__snapshots__/EditCourseForm.test.jsx.snap
src/components/ReduxFormCreatableSelect/index.jsx
src/data/services/DiscoveryDataApiService.js
src/utils/validation.js

This PR adds a searchable dropdown for course tags field. The tags are fetched async from the backend based on user input. 
1. Go to a course page and navigate to the **Topics** section in Course Details.
2. Add topics of your choice or select from the available ones.
3. You can click on any chip to remove the tag from the course.
4. Don't forget to Save the course at the end.
https://user-images.githubusercontent.com/87228907/210012888-2658d9d5-878f-43e4-b6a5-f8cc50f5581e.mov

feat: add searchable dropdown for course tags

---

src/components/StafferPage/StafferForm.jsx
src/components/StafferPage/__snapshots__/StafferForm.test.jsx.snap

This PR makes the organization field editable in instructor forms
1. Go to `/instructors/new`. Try creating an instructor of your choice.
2. Type in an organization field of your choice
3. Hit `Create`
4. Verify that the instructor has indeed been created in discovery admin.

fix: make organization field editable in instructor form

---

src/components/DateTimeField/index.jsx

[PROD-3095](https://2u-internal.atlassian.net/browse/PROD-3095)
This PR updates the `DateTimeField` component to store the time. Previously, the time-named field was using the `updateDate` method on the `onChange` event to change the state of time but because of an invalid date format, the time was not stored. This PR fixes that issue.
Testing Instructions:
- Run the frontend-app-publisher locally
- Visit the localhost:18400/courses/{course.uuid} page.
(You can do this on any of the existing courses)
- Navigate to the course run form of the course
- Verify you can update `Upgrade deadline override time (UTC)` on onChange event
> Error
https://user-images.githubusercontent.com/78806673/212697202-dc50288a-23fa-42a2-b359-4b07b276c290.mov …

fix: update DateTime field to update custom time

---

src/components/EditCoursePage/EditCourseForm.jsx
src/components/EditCoursePage/EditCoursePage.test.jsx
src/components/EditCoursePage/GeoLocationFields.jsx
src/components/EditCoursePage/__snapshots__/EditCourseForm.test.jsx.snap
src/components/EditCoursePage/__snapshots__/EditCoursePage.test.jsx.snap
src/components/EditCoursePage/index.jsx
src/data/actions/courseInfo.js
src/utils/validation.js
src/utils/validation.test.js

- Add Geolocation fields on Course edit, visible to Administrator/staff only
- All 3 fields must be provided to update the data on the backend.
- Backend PR: (https://github.com/openedx/course-discovery/pull/3776) -- must be merged before merging this
- Verify that fields are optional and  do not impact form submissions if not provided
- Verify the backend does not create/update if all 3 are not provided

feat: add Geolocation fields on course edit page

---

src/components/EditCoursePage/__snapshots__/EditCourseForm.test.jsx.snap
src/helpText.jsx

[PROD-3240](https://2u-internal.atlassian.net/browse/PROD-3240)
This PRs updates `url slug` tooltip message on Course Edit Page

chore: update url slug tooltip

---

src/data/actions/courseInfo.js
src/data/actions/courseInfo.test.js

In certain cases of edits, the Save & Re-publish would not change to the disabled "Changes Saved" button after the API call has been completed. This happens when the backend has changed the form values in one way or another in the returned response. On publisher, if the form values do not match returned values, it treats as if the edits are still in progress. That is also why refreshing the page fixed the button because form values are populated with the latest DB data returned by API. 
This PR adds a few fields, that can be edited by backend, to sync their data with form data via a redux change to ensure the button moves to the correct state and provide feedback to the editor that the operation was successful.
- Run publisher on your local. Make sure studio, ecommerce, and discovery are …

fix: add redux change to update fields changed by backend

---

src/components/RichEditor/__snapshots__/RichEditor.test.jsx.snap
src/components/RichEditor/index.jsx

[PROD-3220] (https://2u-internal.atlassian.net/browse/PROD-3220)
This PR add the directionality plugin to tinyMCE editor and add the directionality button to the toolbar of the editor to allow the user to change the direction of the text (RTL or LTR). 
I've already whitelisted dir attribute for paragraphs in the PR: https://github.com/openedx/course-discovery/pull/3908
https://github.com/openedx/frontend-app-publisher/assets/78806673/1f793a60-c244-42ae-a16e-cb36030715ed

feat: add directionality plugin to the tinyMCE

---

.gitignore
Makefile
package-lock.json
package.json
src/components/EditCoursePage/EditCoursePage.test.jsx
src/components/Pill/Pill.test.jsx
src/components/Pill/__snapshots__/Pill.test.jsx.snap
src/components/Pill/index.jsx
src/components/Pill/messages.js
src/containers/MainApp/index.jsx
src/i18n/index.js
src/index.jsx
src/sass/App.scss
src/setupTest.js

feat: use `atlas` in `make pull_translations`
Changes
-------
- Bump frontend-platform to bring `intl-imports.js` script
- Move all i18n imports into `src/i18n/index.js` so `intl-imports.js` can override it with latest translations
- Add `atlas` into `make pull_translations` when `OPENEDX_ATLAS_PULL` environment variable is set.
Testing
-------
References
----------
This pull request is part of the [FC-0012 project](https://openedx.atlassian.net/l/cp/XGS0iCcQ) which is sparked by the [Translation Infrastructure update OEP-58](https://open-edx-proposals.readthedocs.io/en/latest/architectural-decisions/oep-0058-arch-translations-management.html#specification).
Up-to-date project overview and details are available in the [Approach Memo and Technical Discovery: Translations Infrastructure …

feat: use `atlas` in `make pull_translations`

---

src/components/EditCoursePage/EditCourseForm.test.jsx
src/components/EditCoursePage/__snapshots__/EditCourseForm.test.jsx.snap
src/data/constants/index.js
src/utils/index.js
src/utils/utils.test.js

Description
---------------
This PR fixes regex pattern for URL slug field.
- Enter the current url slug pattern (Alphanumeric, -, _) and check if it is working properly, Enter the invalid slugs as well to check the validity
- Update `IS_NEW_SLUG_FORMAT_ENABLED` value from `.env.development` file to true and check if it is accepting both updated & old url slug for OCM courses if none of its course in `POST REVIEW` or `IN REVIEW` state and old format slug for remaining

fix: regex pattern for slug pattern

---

src/data/constants/index.js
src/utils/index.js
src/utils/utils.test.js

[PROD-3449](https://2u-internal.atlassian.net/browse/PROD-3449)
------------------
This PR temporarily allows normal slug format even if `learn` slug format is enabled
- Enter the current url slug pattern (Alphanumeric, -, _) and check if it is working properly. Enter invalid slugs and check appropriate message is displayed.
- Update `IS_NEW_SLUG_FORMAT_ENABLED` value from `.env.development` file to true and check if it is accepting both updated & old url slug for OCM courses and only old url format for other courses.  **Check that behavior for OCM courses is same in case of both published and unpublished courses**
You may get validation errors on the backend with `learn` format slugs. You can either ignore them or comment out [this line in …

feat: allow both slug formats until complete rollout

---

src/utils/index.js

Courses with type `empty` are not editable in publisher. This PR attempts to fix that.

fix: make courses with type empty editable in publisher

---

src/utils/index.js
src/utils/utils.test.js

When a new course or course run is created, the [nonEmexptField](https://github.com/openedx/frontend-app-publisher/blob/6f75320c9ee491c6875e3dbbffb9a53f9c358166/src/utils/index.js#L134) checks for course run for newly created run fail with the error "that undefined does not have `expected_program_name` field". 
This is happening because when a new run is created, the redux form state does not update to include the new run. This line `const index = currentRuns.findIndex(run => run.key === runKey);` returns -1 because new run is not present in form fields. The -1 index then causes undefined error on the upcoming lines in the exempt checks.
To counter this, do not perform the exempt checks on the newly created run because the form is not rendered yet and technically, there are no edits in …

fix: skip nonExempt changes check for newly created runs that do not appear in form

---

decisions/0006-program-slugs-in-publisher.rst

[PROD-3495](https://2u-internal.atlassian.net/browse/PROD-3495)
ADR for adding programs on Publisher for SEO teams. Teams will be able to see programs and edit program slugs on Publisher.

docs: ADR for bringing programs in Publisher

---

src/components/EditCoursePage/EditCourseForm.jsx
src/components/EditCoursePage/EditCourseForm.test.jsx
src/components/EditCoursePage/__snapshots__/EditCourseForm.test.jsx.snap

[PROD-3570]()
-------------------
This PR updates disabled condition for Watchers Field. Now the watchers field is editable only if either of its course runs is in PRE_REVIEWED_STATUSES (`UNPUBLISHED`, `REVIEW_BY_LEGAL`, `REVIEW_BY_INTERNAL`)

chore: update watcher field disabled condition

---

src/components/EditCoursePage/CollapsibleCourseRun.jsx
src/components/EditCoursePage/__snapshots__/CollapsibleCourseRun.test.jsx.snap
src/utils/validation.js
src/utils/validation.test.js

Do not require staff when submitting course runs. This is applicable for both OCs & non-OCs (ExecEd & Bootcamps)
- Open any course on publisher
- Create a new run for the course. Add required information but dont add Staff information. Notice the staff field will now mention that staff is optional.
- Submit run for review. The run will be submitted for review.
- Complete the review cycle for course run. No staff related error will be raised.

feat: do not require staff when submitting runs

---

src/data/constants/index.js
src/setupTest.js
src/utils/utils.test.js

[PROD-3592](https://2u-internal.atlassian.net/browse/PROD-3592)
------------
This PR adds the test in publisher to verify the URL slug format for bootcamps.

chore: add subdirectory slug format for bootcamps

---

src/components/EditCoursePage/CollapsibleCourseRun.jsx
src/components/EditCoursePage/CollapsibleCourseRun.test.jsx
src/components/EditCoursePage/EditCoursePage.test.jsx
src/components/EditCoursePage/__snapshots__/CollapsibleCourseRun.test.jsx.snap
src/components/EditCoursePage/__snapshots__/EditCoursePage.test.jsx.snap
src/components/EditCoursePage/index.jsx
src/helpText.jsx
src/utils/index.js
src/utils/utils.test.js

[PROD-3742]()
-------
This PR adds variant_id to CourseRunForm and make it visible only for external courses

feat: add variant ID field CourseRun form

---

src/components/SidePanes/CatalogInclusionPane.jsx
src/components/SidePanes/CatalogInclusionPane.test.jsx

https://2u-internal.atlassian.net/browse/ENT-8076
Previously, we only allowed you to toggle the enterprise subscription inclusion if your course run was published, but now we are also allowing it if it is reviewed and scheduled. In response to a bug filed by a Harvard customer.

fix: include reviewed to allowed statuses

---

src/components/EditCoursePage/EditCourseForm.jsx
src/components/EditCoursePage/__snapshots__/EditCourseForm.test.jsx.snap

https://2u-internal.atlassian.net/browse/PROD-3862
Change helptext for course type field.

chore: update helptext

---

src/data/actions/courseInfo.js

[PROD-4013](https://2u-internal.atlassian.net/browse/PROD-4013)
Fixes `Cannot read properties of undefined (reading 'heading')` due to null additional_metadata after a save.

fix: reading undefined additional metadata

---

src/data/constants/index.js
src/data/services/DiscoveryDataApiService.js
src/utils/index.js

[PROD-4088](https://2u-internal.atlassian.net/browse/PROD-4088)
-------
This PR adds adds the restriction params to the API calls in Publisher to ensure that restricted runs are always fetched/updated properly in Publisher.
1. Check out this branch
2. Open/Create an executive education course in publisher
3. Add a restriction type. Then change it. Finally remove it. 
4. Verify that the behavior is as expected.

fetch restricted runs in publisher

---

src/components/EditCoursePage/EditCourseForm.jsx
src/components/EditCoursePage/EditCourseForm.test.jsx
src/components/EditCoursePage/__snapshots__/EditCourseForm.test.jsx.snap

It can happen that the collaborators have not been fetched before the page renders. This causes the collaborators to evaluate to undefined raising TypeErrors later when we try to use a `.map` on them

fix: add default value when destructuring collaborator options

---

src/components/EditCoursePage/__snapshots__/CollapsibleCourseRun.test.jsx.snap
src/setupTest.js

[PROD-3142](https://2u-internal.atlassian.net/browse/PROD-3142)
--------
This PR removes the workaround for ignoring unhandledPromiseRejection warnings. Previously, unhandledPromiseRejection warnings were converted to errors in Node.js 15, when we run tests on Node.js 16 so this workaround added at that time.

chore: remove unhandledPromiseRejection Error in Frontend-app-publisher

---

src/components/EditCoursePage/EditCourseForm.jsx
src/components/EditCoursePage/EditCourseForm.test.jsx
src/components/EditCoursePage/__snapshots__/EditCourseForm.test.jsx.snap
src/containers/MainApp/index.jsx

- Disable price edit if a course has published runs (this is temporary and will be removed)
- Only display sitewide banner if there is some content to display. The default banner without any content was always displaying and did not look alright.

temp: disable price edits if course has a published run

---

src/components/EditCoursePage/EditCourseForm.jsx
src/components/EditCoursePage/EditCourseForm.test.jsx

[PROD-3254](https://2u-internal.atlassian.net/browse/PROD-3254)
This PR puts Level Type and Primary Subject as non-marketable fields i.e. make them optional for masters courses (and all the non-marketable courses)

feat: make level type and subjects field optional for masters courses

---

README.md

- **docs: Fully convert README to markdown** (it was half in MD and half in RST, changed to md to match the style of other fea- repos)
- **docs: Update README to point to Tutor**

Update README: Convert to MD and mention Tutor install

---

src/components/RichEditor/RichEditor.test.jsx
src/components/RichEditor/index.jsx

Only update if the editor is actually dirty (user made changes)
This prevents Redux Form from being marked dirty due to TinyMCE normalization

Skip char count update if editor not dirty

---

src/components/CreateCourseRunPage/CreateCourseRunPage.test.jsx

This PR fixes a test by awaiting `waitFor`, and using a real redux store, as the mock store does not allow updates.

fix: broken test

---

src/components/CreateCourseRunPage/CreateCourseRunForm.jsx
src/components/CreateCourseRunPage/index.jsx
src/containers/CreateCourseRun/index.jsx

[PROD-4403](https://2u-internal.atlassian.net/browse/PROD-4403)
------------
ReduxForm "[loses](https://github.com/redux-form/redux-form/issues/4152)" initialValues when a form is unmounted and remounted. This is what react StrictMode aims to [emulate](https://react.dev/reference/react/StrictMode#fixing-bugs-found-by-re-running-effects-in-development) (among other things), hence causing the `CreateCourseRunForm` to break in StrictMode. 
As a workaround, we set the `destroyOnUnmount` setting to `false`, which prevents redux-form from clearing the form redux state (which includes `initialValues`) on an unmount. Since we are not destroying the state on an unmount, just to be extra-safe, I have also changed the ids for the form based on the course being rerun, so that the states for separate …

fix: create course run form in strict mode

---

src/components/BulkOperationDetailsPage/BulkOperationDetails.jsx
src/components/BulkOperationDetailsPage/index.jsx
src/components/BulkOperationDetailsPage/styles.scss
src/components/BulkOperations/BulkOperations.scss
src/components/BulkOperations/index.jsx
src/components/CollaboratorPage/CollaboratorForm.jsx
src/components/EditCoursePage/__snapshots__/CollapsibleCourseRun.test.jsx.snap
src/components/EditCoursePage/__snapshots__/EditCourseForm.test.jsx.snap
src/components/EditCoursePage/__snapshots__/EditCoursePage.test.jsx.snap
src/components/Pill/__snapshots__/Pill.test.jsx.snap
src/components/Pill/index.jsx
src/components/SidePanes/Pane.jsx
src/components/SitewideBanner/index.jsx
src/components/StafferPage/AreasOfExpertise.jsx
src/components/StafferPage/SocialLinks.jsx
src/components/StafferPage/StafferForm.jsx
src/components/StafferPage/StafferForm.scss
src/components/StafferPage/__snapshots__/AreasOfExpertise.test.jsx.snap
src/components/StafferPage/__snapshots__/SocialLinks.test.jsx.snap
src/components/StafferPage/__snapshots__/StafferForm.test.jsx.snap
src/components/StafferPage/__snapshots__/StafferPage.test.jsx.snap
src/sass/App.scss

This PR fixes UI inconsistencies across all Publisher pages to align with updated design tokens introduced platform-wide.
ticket for this - https://2u-internal.atlassian.net/browse/PROD-4404
Key Changes:
1.Main Page: Unified pill badge styles for consistent size, font, and alignment.
Before
After
2.Course Details Page: Standardized side pane header styling and icon sizing.
Before
After
3.New Staff Page: Applied consistent styles to all buttons (font, color, border, radius).
Before
After
4.New Collaborator Page: Aligned cancel and create button styles with updated tokens.
Before
After
5.Bulk Operations Page: Customized with consistent border, font, and focus styles.
Before
After
6.Bulk Operation Details Page: Standardized button styles for CSV actions (download/preview).
Before
After

fix: UI inconsistencies across all Publisher pages
